import { SurveyQuestion } from "@/types/types";

export const questions: SurveyQuestion[] = [
  {
    id: "workflow_type",
    type: "radio",
    question: "Which type of workflow do you want to automate?",
    options: [
      "Invoice Processing",
      "Customer Service",
      "HR Onboarding",
      "Recruitment",
      "Data Entry",
      "Inventory Management",
      "Other",
    ],
    required: true,
    followUp: {
      id: "workflow_type_other",
      type: "text",
      question: "Please specify the workflow type:",
      required: true,
      condition: { field: "workflow_type", value: "Other" },
    },
  },
  {
    id: "current_process",
    type: "textarea",
    question:
      "Describe the current workflow step-by-step, including who is involved, what tools are used, and how data flows between steps:",
    required: true,
    placeholder:
      "E.g., '1. Receive invoice via email. 2. Manually enter data into Salesforce. 3. Approve in Ariba. 4. Notify team via Slack.'",
  },
  {
    id: "triggers",
    type: "checkbox",
    question: "What events should trigger this workflow?",
    options: [
      "New email received",
      "Form submission",
      "API call or webhook",
      "Scheduled time (e.g., daily)",
      "Manual trigger",
      "Other",
    ],
    required: true,
    followUp: {
      id: "triggers_other",
      type: "text",
      question: "Please specify the trigger:",
      required: true,
      condition: { field: "triggers", value: "Other" },
    },
  },
  {
    id: "pain_points",
    type: "checkbox",
    question: "What challenges do you face in this workflow?",
    options: [
      "Time-consuming manual data entry",
      "Frequent data errors or inconsistencies",
      "Lack of real-time visibility or tracking",
      "Delays in approvals or processing",
      "Poor communication between teams",
      "Difficulty integrating systems",
      "Other",
    ],
    required: true,
    followUp: {
      id: "pain_points_other",
      type: "text",
      question: "Please describe the other challenge:",
      required: true,
      condition: { field: "pain_points", value: "Other" },
    },
  },
  {
    id: "systems",
    type: "checkbox",
    question: "Which systems or tools are currently used in this workflow?",
    options: [
      "Email (Gmail, Outlook, etc.)",
      "Salesforce",
      "SAP",
      "Ariba",
      "Bill.com",
      "Kronos",
      "Microsoft Office (Excel, Word, etc.)",
      "Google Workspace (Sheets, Docs, etc.)",
      "Slack",
      "Custom internal systems or APIs",
      "Other",
    ],
    required: true,
    followUp: {
      id: "systems_other",
      type: "text",
      question: "Please specify the other system or tool:",
      required: true,
      condition: { field: "systems", value: "Other" },
    },
  },
  {
    id: "api_access",
    type: "radio",
    question: "Do you have API access or credentials for the systems involved?",
    options: ["Yes, for all systems", "Yes, for some systems", "No", "Unsure"],
    required: true,
    followUp: {
      id: "api_access_details",
      type: "textarea",
      question:
        "Please provide details (e.g., which systems, types of API access):",
      required: true,
      condition: {
        field: "api_access",
        value: ["Yes, for all systems", "Yes, for some systems"],
      },
    },
  },
  {
    id: "outputs",
    type: "checkbox",
    question: "What outputs or actions should the automated workflow produce?",
    options: [
      "Update a system (e.g., Salesforce, Ariba)",
      "Send notifications (e.g., email, Slack)",
      "Generate reports or files",
      "Trigger another workflow",
      "Interact with users (e.g., via chat or email)",
      "Other",
    ],
    required: true,
    followUp: {
      id: "outputs_other",
      type: "text",
      question: "Please specify the other output or action:",
      required: true,
      condition: { field: "outputs", value: "Other" },
    },
  },
  {
    id: "agent_interaction",
    type: "checkbox",
    question:
      "If user interaction is needed, which communication channels should the workflow support?",
    options: [
      "Chat (e.g., web interface)",
      "Email",
      "Slack",
      "Phone or SMS",
      "Video call",
      "None",
    ],
    required: true,
  },
  {
    id: "volume",
    type: "radio",
    question: "What is the approximate monthly volume of this workflow?",
    options: [
      "Less than 100 instances",
      "100-500 instances",
      "500-1,000 instances",
      "More than 1,000 instances",
    ],
    required: true,
  },
  {
    id: "priority",
    type: "scale",
    question: "How critical is automating this workflow? (1 = Low, 5 = High)",
    min: 1,
    max: 5,
    required: true,
  },
  {
    id: "additional_info",
    type: "textarea",
    question:
      "Any additional details about the workflow or automation preferences?",
    required: false,
    placeholder:
      "E.g., specific compliance requirements, preferred vendors, or constraints.",
  },
];
